language: php
php:
    - 5.4
    - 5.5
    - 5.6

script: vendor/bin/tester tests/TestCases/GlobalProvider.phpt -s -c tests/php-unix.ini; vendor/bin/tester tests/TestCases/MethodProvider.phpt -s -c tests/php-unix.ini

after_failure:
    # Print *.actual content
    - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

before_script:
    # Install Nette Tester
    - composer install --no-interaction --dev --prefer-source
    - mysql -e 'create database testing;'
